{
 "title": "DMT",
 "description": "Dashboard for DMT metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "OPENSHIFT_CLUSTER", "label": "Cluster", "query": "prometheus" },
   {
    "name": "NAMESPACE",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"dmt.*\"}, namespace)"
    }
   },
   { "name": "TABLE", "label": "table", "query": { "query": "metrics(.*table_size$)" } }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}",
     "legendFormat": "{{instance}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}*1000",
     "legendFormat": "{{instance}} - {{pod}}"
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}[10m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}[10m]))/sum(rate(http_server_requests_seconds_count{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}[10m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=\"500\", pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}[10m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  { "title": "Table overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Table count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "table_count{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}",
     "legendFormat": "{{instance}} - {{pod}}"
    }
   ]
  },
  {
   "title": "$TABLE",
   "type": "stat",
   "description": "Size of selected table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "$TABLE{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}",
     "legendFormat": "{{instance}} - {{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Edpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{status=\"200\", pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}",
     "legendFormat": "200 Requests"
    },
    {
     "expr": "http_server_requests_seconds_count{status=\"500\", pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}",
     "legendFormat": "500 Requests"
    },
    {
     "expr": "http_server_requests_seconds_count{status=\"RESET\", pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}",
     "legendFormat": "Reset requests"
    }
   ]
  },
  {
   "title": "Total number of requests per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}[10m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Average inbound request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}[5m]) / rate(http_server_requests_seconds_count{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}[5m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Maximum inbound request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Sum of the duration of every request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}[5m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{pod=~\"dmt.*\", namespace=\"$NAMESPACE\", clusterName=\"$OPENSHIFT_CLUSTER\"}",
     "legendFormat": "cpus"
    }
   ]
  }
 ]
}