{
 "title": "Debezium connectors",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "OPENSHIFT_CLUSTER", "label": "Cluster", "query": "prometheus" },
   {
    "name": "CONNECTOR_TYPE",
    "label": "Connector Type",
    "query": "debezium_metrics_totalnumberofeventsseen{clusterName=~\"$OPENSHIFT_CLUSTER\"}"
   },
   {
    "name": "NAMESPACE",
    "label": "Namespace",
    "query": "debezium_metrics_totalnumberofeventsseen{clusterName=~\"$OPENSHIFT_CLUSTER\"}"
   },
   {
    "name": "CONNECT_CLUSTER",
    "label": "Connect cluster",
    "query": "debezium_metrics_totalnumberofeventsseen{clusterName=~\"$OPENSHIFT_CLUSTER\"}"
   },
   {
    "name": "POD_NAME",
    "label": "Pod name",
    "query": "debezium_metrics_totalnumberofeventsseen{clusterName=~\"$OPENSHIFT_CLUSTER\"}"
   },
   {
    "name": "CONNECTOR_NAME",
    "label": "Connector Name",
    "query": {
     "query": "debezium_metrics_totalnumberofeventsseen{plugin=\"$CONNECTOR_TYPE\", clusterName=~\"$OPENSHIFT_CLUSTER\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connect response rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_metrics_response_rate{strimzi_io_cluster=~\"$CONNECT_CLUSTER\", clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}"
    }
   ]
  },
  {
   "title": "Binlog position",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_binlogposition{plugin=\"$CONNECTOR_TYPE\",name=\"$CONNECTOR_NAME\", strimzi_io_cluster=~\"$CONNECT_CLUSTER\", clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}"
    }
   ]
  },
  { "title": "Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Time since last event",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(1, debezium_metrics_millisecondssincelastevent{context=~\"(binlog|streaming)\", plugin=\"$CONNECTOR_TYPE\",name=\"$CONNECTOR_NAME\", strimzi_io_cluster=~\"$CONNECT_CLUSTER\", clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"})"
    }
   ]
  },
  {
   "title": "Event count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 3, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{context=~\"(binlog|streaming)\", plugin=\"$CONNECTOR_TYPE\",name=\"$CONNECTOR_NAME\", strimzi_io_cluster=~\"$CONNECT_CLUSTER\", clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}",
     "legendFormat": "Total events received"
    },
    {
     "expr": "debezium_metrics_numberofskippedevents{context=~\"(binlog|streaming)\", plugin=\"$CONNECTOR_TYPE\",name=\"$CONNECTOR_NAME\", strimzi_io_cluster=~\"$CONNECT_CLUSTER\", clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}",
     "legendFormat": "Events skipped"
    }
   ]
  },
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_connected{plugin=\"$CONNECTOR_TYPE\",name=\"$CONNECTOR_NAME\", strimzi_io_cluster=~\"$CONNECT_CLUSTER\", clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}"
    }
   ]
  },
  {
   "title": "Remaining queue capacity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_queueremainingcapacity{plugin=\"$CONNECTOR_TYPE\",name=\"$CONNECTOR_NAME\", strimzi_io_cluster=~\"$CONNECT_CLUSTER\", clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}",
     "legendFormat": "Remaining queue capacity"
    }
   ]
  },
  {
   "title": "Snapshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_totaltablecount{plugin=\"$CONNECTOR_TYPE\",name=\"$CONNECTOR_NAME\", strimzi_io_cluster=~\"$CONNECT_CLUSTER\", clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Remaining tables",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_remainingtablecount{context=\"snapshot\", plugin=\"$CONNECTOR_TYPE\",name=\"$CONNECTOR_NAME\", strimzi_io_cluster=~\"$CONNECT_CLUSTER\", clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}",
       "legendFormat": "Remaining"
      }
     ]
    },
    {
     "title": "Running snapshot",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_snapshotrunning{plugin=\"$connector_type\",name=\"$connector_name\",context=\"snapshot\", clusterName=~\"$OPENSHIFT_CLUSTER\"}"
      }
     ]
    },
    {
     "title": "Completed",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_snapshotcompleted{context=\"snapshot\", plugin=\"$CONNECTOR_TYPE\",name=\"$CONNECTOR_NAME\", strimzi_io_cluster=~\"$CONNECT_CLUSTER\", clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}"
      }
     ]
    },
    {
     "title": "Aborted",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_snapshotaborted{context=\"snapshot\",plugin=\"$CONNECTOR_TYPE\",name=\"$CONNECTOR_NAME\", strimzi_io_cluster=~\"$CONNECT_CLUSTER\", clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}"
      }
     ]
    },
    {
     "title": "Event count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "debezium_metrics_totalnumberofeventsseen{context=\"snapshot\",plugin=\"$CONNECTOR_TYPE\",name=\"$CONNECTOR_NAME\", strimzi_io_cluster=~\"$CONNECT_CLUSTER\", clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}",
       "legendFormat": "Total events received"
      }
     ]
    }
   ]
  },
  { "title": "Kafka Connect", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Network traffic rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_metrics_incoming_byte_rate{clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}",
     "legendFormat": "Incoming({{client}})"
    },
    {
     "expr": "kafka_connect_metrics_outgoing_byte_rate{clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}",
     "legendFormat": "Outgoing({{client}})"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area='heap', clusterName=~\"$OPENSHIFT_CLUSTER\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_bytes_max{area='heap', clusterName=~\"$OPENSHIFT_CLUSTER\"}",
       "legendFormat": "Maximum"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}",
       "legendFormat": "Running"
      },
      {
       "expr": "jvm_threads_peak{clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}",
       "legendFormat": "Maximum"
      },
      {
       "expr": "jvm_threads_started_total{clusterName=~\"$OPENSHIFT_CLUSTER\", namespace=~\"$NAMESPACE\", kubernetes_pod_name=~\"$POD_NAME\"}",
       "legendFormat": "Started in total"
      }
     ]
    }
   ]
  }
 ]
}