{
 "title": "Alerts by Cluster",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "query_result(instance:node_num_cpu:sum)"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": {
     "query": "label_values(ALERTS{clusterName=\"$cluster\"}, severity)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Real Time Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alert Severity",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\", clusterName=\"$cluster\"}) by (severity)",
     "legendFormat": "{{ severity }}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Firing Alerts Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\", clusterName=\"$cluster\", severity=~\"$severity\"}) by (alertname)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Pending Alerts Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"pending\", clusterName=\"$cluster\", severity=~\"$severity\"}) by (alertname)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Alerts over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\", clusterName=\"$cluster\", severity=~\"$severity\" }) by (alertname)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  }
 ]
}