{
 "title": "Skodjob Scenario Overview",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Infra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clusters version",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(cluster_version{type=\"cluster\"}) by (version, cluster, type, from_version)"
    },
    {
     "expr": "(count(sum by (image, cluster) (max_over_time(cluster_version{type=\"completed\"}[$__range]))) by (cluster)) - 1",
     "legendFormat": "{{value}}"
    },
    {
     "expr": "apiserver_request_duration_seconds:histogram_quantile_99 > 0",
     "legendFormat": "{{value}}"
    }
   ]
  },
  { "title": "Scenario Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Strimzi Cluster Operators",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_memory_usage_bytes{container=\"strimzi-cluster-operator\"})"
    }
   ]
  },
  {
   "title": "Available Strimzi Operators",
   "type": "table",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"strimzi-cluster-operator\"}"
    }
   ]
  },
  {
   "title": "Created Resoruces Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "strimzi_resource_state{kind!=\"KafkaTopic\"}"
    }
   ]
  },
  {
   "title": "Kafka Readiness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(strimzi_resource_state{kind=\"Kafka\"}) by (name, kind, clusterName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KafkaMirrorMaker2 Readiness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(strimzi_resource_state{kind=\"KafkaMirrorMaker2\"}) by (name, kind, clusterName)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Test suite status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Passed tests",
   "type": "stat",
   "description": "Number of passed test cases",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(sum (tealc_tests_passed_tests_total) by (testSuiteName, prometheus_pod)) by (testSuiteName))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed tests",
   "type": "stat",
   "description": "Number of failed test cases",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(sum (tealc_tests_failed_tests_total) by (testSuiteName, prometheus_pod)) by (testSuiteName))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flaky tests",
   "type": "stat",
   "description": "Number of flaky test cases",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(sum (tealc_tests_flaky_tests_total) by (testSuiteName, prometheus_pod)) by (testSuiteName))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Passed per Test Suite",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg(sum (tealc_tests_passed_tests_total) by (testSuiteName, prometheus_pod)) by (testSuiteName)",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  {
   "title": "Failures per Test Suite",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "avg(sum (tealc_tests_failed_tests_total) by (testSuiteName, prometheus_pod)) by (testSuiteName)",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  {
   "title": "Flaky tests per Test Suite",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "avg(sum (tealc_tests_flaky_tests_total) by (testSuiteName, prometheus_pod)) by (testSuiteName)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}