{
 "title": "Strimzi Canary",
 "tags": [
  "Strimzi",
  "Kafka"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Clients status",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(strimzi_canary_records_consumed_total[5m]) * 60",
     "legendFormat": "{{clientid}}-{{partition}}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consumed records",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_canary_records_consumed_total)"
    }
   ]
  },
  {
   "title": "Consuming rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(strimzi_canary_records_consumed_total[5m])*60)"
    }
   ]
  },
  {
   "title": "Produced records",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_canary_records_produced_total)"
    }
   ]
  },
  {
   "title": "Producing rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(strimzi_canary_records_produced_total[5m])*60)"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Average record producing latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(strimzi_canary_records_produced_latency_sum{clientid=\"strimzi-canary-client\"}[5m])/rate(strimzi_canary_records_produced_latency_count{clientid=\"strimzi-canary-client\"}[5m])",
     "legendFormat": "{{clientid}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Average record consuming latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(strimzi_canary_records_consumed_latency_sum{clientid=\"strimzi-canary-client\"}[5m])/rate(strimzi_canary_records_consumed_latency_count{clientid=\"strimzi-canary-client\"}[5m])",
     "legendFormat": "{{clientid}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Record consuming performance index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(strimzi_canary_records_consumed_latency_bucket{le=\"400\"}[5m])/rate(strimzi_canary_records_consumed_latency_bucket[5m])*100",
     "legendFormat": "{{clientid}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Record producing performance index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(strimzi_canary_records_produced_latency_bucket{le=\"400\"}[5m])/rate(strimzi_canary_records_produced_latency_bucket[5m])*100",
     "legendFormat": "{{clientid}}-{{partition}}"
    }
   ]
  }
 ]
}